# Generated by Django 2.0 on 2019-02-23 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techno', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('ajout', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'compétence',
                'ordering': ['techno'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('ecole', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('obtenu', models.CharField(max_length=255, null=True)),
                ('debut', models.DateField(verbose_name='date de début')),
                ('fin', models.DateField(verbose_name='date de fin')),
                ('ajout', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'diplôme',
                'ordering': ['debut'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=255)),
                ('employeur', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('debut', models.DateField(verbose_name='date de début')),
                ('fin', models.DateField(verbose_name='date de fin')),
                ('ajout', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'expérience',
                'ordering': ['debut'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.TextField()),
                ('photo', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('age', models.DateField(verbose_name='Date de naissance')),
                ('mail', models.EmailField(max_length=254)),
                ('ajout', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'info',
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('lien', models.URLField(max_length=255)),
                ('ajout', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'réalisation',
                'ordering': ['ajout'],
            },
        ),
    ]
