# Generated by Django 2.0 on 2019-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
    ]
