# Generated by Django 2.0 on 2019-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20190223_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='code',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
